[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Test Smell Catalog"
authors = [{name = "EASY LAB - Universidade Federal de Alagoas (UFAL)", email = "easy@ic.ufal.br"}]
dynamic = ["version", "description"]
